#
# IMPORTANT NOTE
#
# This chart inherits from a common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

controllers:
  main:
    containers:
      main:
        image:
          # -- image repository
          repository: ghcr.io/reitermarkus/7d2d
          # -- image tag
          # @default -- chart.appVersion
          tag:
          # -- image pull policy
          pullPolicy: Always
        # -- environment variables. See more environment variables in the [7d2d documentation](https://github.com/reitermarkus/7d2d).
        # @default -- See below
        env:
          # -- Set the container timezone
          TZ: UTC
          # VERSION: alpha20.2
          # SERVER_NAME: My 7 Days to Die Server
        ports:
          - name: serverquery
            containerPort: 26900
          - name: serverlist
            containerPort: 26900
            protocol: UDP
          - name: steam
            containerPort: 26901
            protocol: UDP
    pod:
      # -- Configure the Security Context for the Pod
      podSecurityContext: {}
        # fsGroup: 1000
      # -- The server binary is only available for x86_64.
      nodeSelector:
        kubernetes.io/arch: amd64

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        enabled: false
        primary: false
      serverquery:
        primary: true
        enabled: true
        port: 26900
        targetPort: serverquery
      serverlist:
        enabled: true
        port: 26900
        targetPort: serverlist
        protocol: UDP
      steam:
        enabled: true
        port: 26901
        targetPort: steam
        protocol: UDP

probes:
  startup:
    spec:
      # Initial installation and verifying updates can take a while.
      failureThreshold: 120
      initialDelaySeconds: 30

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: false
  server:
    enabled: false
