---
apiVersion: v2
appVersion: 1.18.1
description: FreshRSS is a self-hosted RSS feed aggregator
name: freshrss
version: 6.4.2
kubeVersion: ">=1.16.0-0"
keywords:
  - freshrss
  - rss
home: https://github.com/reitermarkus/helm-charts/tree/main/charts/freshrss
icon: https://avatars.githubusercontent.com/u/9414285?s=200&v=4
sources:
  - https://github.com/FreshRSS/FreshRSS
  - https://hub.docker.com/r/linuxserver/freshrss
maintainers:
  - name: reitermarkus
    email: me@reitermark.us
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 1.0.0
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
