#
# IMPORTANT NOTE
#
# This chart inherits from a common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: mumblevoip/mumble-server
  # -- image tag
  # @default -- chart.appVersion
  tag: v1.4.287
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [mumble-server image documentation](https://github.com/mumble-voip/mumble-docker#configuration).
# @default -- See below
env:
  TZ: UTC
  MUMBLE_CONFIG_WELCOMETEXT: <br/>Welcome to this server, running the official Mumble Docker image on Kubernetes.<br/>Enjoy your stay!<br/>
  # MUMBLE_CONFIG_SERVER_PASSWORD:
  #   valueFrom:
  #     secretKeyRef:
  #       name: mumble
  #       key: server_password
  # MUMBLE_SUPERUSER_PASSWORD:
  #   valueFrom:
  #     secretKeyRef:
  #       name: mumble
  #       key: superuser_password

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        enabled: false
        primary: false
      control:
        enabled: true
        primary: true
        port: 64738
      voice:
        enabled: true
        port: 64738
        protocol: UDP

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: false
    mountPath: /data

# -- The Mumble docker image is only available for x86_64 (see https://github.com/mumble-voip/mumble-docker/issues/3).
nodeSelector:
  kubernetes.io/arch: amd64
