controllers:
  teamspeak:
    containers:
      server:
        env:
          TS3SERVER_LICENSE: accept

metrics:
  enabled: true
  prometheusRule:
    enabled: false
  serviceMonitor:
    enabled: false
