controllers:
  teamspeak:
    containers:
      server:
        env:
          TS3SERVER_LICENSE: accept

metrics:
  # FIXME: Startup probe is failing.
  # enabled: true
  prometheusRule:
    enabled: false
  serviceMonitor:
    enabled: false
