excluded-charts-lint: []

excluded-charts-install:
  - apps/alertmanager-bot
  - apps/alertmanager-discord
  - apps/amcrest2mqtt
  - apps/facebox
  - apps/factorio
  - apps/foundryvtt
  - apps/heimdall
  - apps/multus
  - apps/pod-gateway
  - apps/promcord
  - apps/reg
  - apps/ser2sock
  - apps/satisfactory
  - apps/zalando-postgres-cluster
  - apps/zigbee2mqtt
  - apps/wireguard
  - incubator/sdtd
  - library/common
