---
{{- include "bjw-s.common.loader.init" . }}

# If there's an existing secret, reuse it, otherwise generate a new one.
{{- define "teamspeak.serveradmin-password" -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "bjw-s.common.lib.chart.names.fullname" .) ) -}}
  {{- if $secret -}}
    {{-  index $secret "data" "serveradmin_password" -}}
  {{- else -}}
    {{- randAlphaNum 32 | b64enc | quote -}}
  {{- end -}}
{{- end -}}

{{- define "teamspeak.harcodedValues" -}}
# Set the nameOverride based on the release name if no override has been set
{{- if not .Values.global.nameOverride }}
global:
  nameOverride: "{{ .Release.Name }}"
{{- end }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "teamspeak.harcodedValues" . | fromYaml) -}}

{{- define "teamspeak.harcodedValues2" -}}
{{- $mainEnv := .Values.controllers.teamspeak.containers.server.env }}
controllers:
  teamspeak:
    containers:
      server:
        env:
          {{- if not $mainEnv.TS3SERVER_SERVERADMIN_PASSWORD }}
          TS3SERVER_SERVERADMIN_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
                key: serveradmin_password
          {{- end }}
      {{- if ne .Values.metrics.enabled false }}
      exporter:
        enabled: true
        env:
          {{- $value := $mainEnv.TS3SERVER_SERVERADMIN_PASSWORD -}}
          {{- if $value -}}
          {{- if kindIs "map" $value }}
          SERVERQUERY_PASSWORD:
            {{- toYaml $value | nindent 12 }}
          {{- else }}
          SERVERQUERY_PASSWORD: {{ quote $value }}
          {{- end }}
          {{- else }}
          SERVERQUERY_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
                key: serveradmin_password
          {{- end }}
      {{- end }}

service:
  metrics:
    enabled: {{ ne .Values.metrics.enabled false }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "teamspeak.harcodedValues2" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}
