{{- if not .Values.controllers.teamspeak.containers.server.env.TS3SERVER_SERVERADMIN_PASSWORD }}
{{- include "bjw-s.common.loader.init" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
type: Opaque
data:
  serveradmin_password: {{ template "teamspeak.serveradmin-password" . }}
{{- end }}
