#
# IMPORTANT NOTE
#
# This chart inherits from a common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

controllers:
  main:
    initContainers:
      update:
        image:
          # -- image repository
          repository: inventree/inventree
          # -- image tag
          tag: "{{ .Chart.AppVersion }}"
          # -- image pull policy
          pullPolicy: IfNotPresent
        command:
          - invoke
          - migrate
        workingDir: /home/inventree
    containers:
      main:
        image:
          # -- image repository
          repository: nginx
          # -- image tag
          tag: 1.25.4
          # -- image pull policy
          pullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 80
      server:
        image:
          # -- image repository
          repository: inventree/inventree
          # -- image tag
          # @default -- chart.appVersion
          tag:
          # -- image pull policy
          pullPolicy: IfNotPresent
        # -- environment variables. See more environment variables in the [InvenTree documentation](https://docs.inventree.org/en/latest/start/config/).
        # @default -- See below
        env:
          # -- Set the container timezone
          # TZ: UTC
          # -- Enable plugin support
          # INVENTREE_PLUGINS_ENABLED: 'true'
          # -- Set the admin user name
          # INVENTREE_ADMIN_USER:
          #   valueFrom:
          #     secretKeyRef:
          #       name: inventree
          #       key: admin_user
          # -- Set the admin password
          # INVENTREE_ADMIN_PASSWORD:
          #   valueFrom:
          #     secretKeyRef:
          #       name: inventree
          #       key: admin_password
          # -- Set the admin email
          # INVENTREE_ADMIN_EMAIL:
          #   valueFrom:
          #     secretKeyRef:
          #       name: inventree
          #       key: admin_password
        probes:
          liveness:
            enabled: true
            type: HTTP
            port: 8000
            path: /
            spec:
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
              initialDelaySeconds: 0
          readiness:
            enabled: true
            type: HTTP
            port: 8000
            path: /
            spec:
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
              initialDelaySeconds: 0
          startup:
            enabled: true
            type: HTTP
            port: 8000
            path: /
            spec:
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
              initialDelaySeconds: 0
      worker:
        image:
          # -- image repository
          repository: inventree/inventree
          # -- image tag
          # @default -- chart.appVersion
          tag:
          # -- image pull policy
          pullPolicy: IfNotPresent
        command:
          - invoke
          - worker


postgresql:
  enabled: true
  image:
    tag: 15.5.0
  auth:
    enablePostgresUser: false
    username: inventree
    database: inventree

redis:
  enabled: true
  sentinel:
    enabled: true
  commonConfiguration: |-
    # Disable AOF persistence.
    appendonly no
    # Disable RDB persistence.
    save ""
  master:
    persistence:
      enabled: false
  replica:
    configuration: |-
      replica-read-only no
    persistence:
      enabled: false
  auth:
    enabled: false

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 80
        targetPort: http

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

configMaps:
  nginx-config:
    data:
      default.conf.template: |-
        server {
          listen 80;

          real_ip_header proxy_protocol;

          location / {
            proxy_set_header      Host              $http_host;
            proxy_set_header      X-Forwarded-By    $server_addr:$server_port;
            proxy_set_header      X-Forwarded-For   $remote_addr;
            proxy_set_header      X-Forwarded-Proto $scheme;
            proxy_set_header      X-Real-IP         $remote_addr;
            proxy_set_header      CLIENT_IP         $remote_addr;

            proxy_pass_request_headers on;

            proxy_redirect off;

            client_max_body_size 100M;

            proxy_buffering off;
            proxy_request_buffering off;

            proxy_pass http://127.0.0.1:8000;
          }

          # Redirect any requests for static files
          location /static/ {
            alias /var/www/static/;
            autoindex on;

            # Caching settings
            expires 30d;
            add_header Pragma public;
            add_header Cache-Control "public";
          }

          # Redirect any requests for media files
          location /media/ {
            alias /var/www/media/;

            # Media files require user authentication
            auth_request /auth;

            # Content header to force download
            add_header Content-disposition "attachment";
          }

          # Use the 'user' API endpoint for auth
          location /auth {
            internal;

            proxy_pass http://127.0.0.1:8000/auth/;

            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header X-Original-URI $request_uri;
          }
        }

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  nginx-config:
    enabled: true
    type: configMap
    name: '{{- (include "bjw-s.common.lib.chart.names.fullname" $) -}}-nginx-config'
    advancedMounts:
      main:
        main:
          - path: /etc/nginx/templates/default.conf.template
            readOnly: true
            subPath: default.conf.template
  data:
    enabled: false
    advancedMounts:
      main:
        update:
          - path: /home/inventree/data
        main:
          - path: /var/www
        server:
          - path: /home/inventree/data
        worker:
          - path: /home/inventree/data
