#
# IMPORTANT NOTE
#
# This chart inherits from a common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

controllers:
  main:
    initContainers:
      update:
        image:
          # -- image repository
          repository: inventree/inventree
          # -- image pull policy
          pullPolicy: IfNotPresent
          # -- image tag
          tag: 0.12.10
        command:
          - sh
          - -c
          - |
            echo "pg_dump version: $(pg_dump --version)" || exit 1
            cd /home/inventree || exit 1
            invoke update
        # FIXME: https://github.com/bjw-s/helm-charts/pull/244
        workingDir: /home/inventree
    containers:
      main:
        image:
          # -- image repository
          repository: nginx
          # -- image pull policy
          pullPolicy: IfNotPresent
          # -- image tag
          tag: 1.25.3
        ports:
          - name: http
            containerPort: 80
      server:
        image:
          # -- image repository
          repository: inventree/inventree
          # -- image pull policy
          pullPolicy: IfNotPresent
          # -- image tag
          tag: 0.12.10
        # -- environment variables. See more environment variables in the [InvenTree documentation](https://docs.inventree.org/en/latest/start/config/).
        # @default -- See below
        env:
          # -- Set the container timezone
          # TZ: UTC
          # -- Enable plugin support
          # INVENTREE_PLUGINS_ENABLED: 'true'
          # -- Set the admin user name
          # INVENTREE_ADMIN_USER:
          #   valueFrom:
          #     secretKeyRef:
          #       name: inventree
          #       key: admin_user
          # -- Set the admin password
          # INVENTREE_ADMIN_PASSWORD:
          #   valueFrom:
          #     secretKeyRef:
          #       name: inventree
          #       key: admin_password
          # -- Set the admin email
          # INVENTREE_ADMIN_EMAIL:
          #   valueFrom:
          #     secretKeyRef:
          #       name: inventree
          #       key: admin_password
        probes:
          liveness:
            enabled: true
            custom: false
            type: TCP
            port: 8000
            spec:
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
              initialDelaySeconds: 0
          readiness:
            enabled: true
            custom: false
            type: TCP
            port: 8000
            spec:
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
              initialDelaySeconds: 0
          startup:
            enabled: true
            custom: false
            type: TCP
            port: 8000
            spec:
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
              initialDelaySeconds: 0
      worker:
        image:
          # -- image repository
          repository: inventree/inventree
          # -- image pull policy
          pullPolicy: IfNotPresent
          # -- image tag
          tag: 0.12.10
        command:
          - invoke
          - worker


postgresql:
  enabled: true
  image:
    tag: 15.5.0
  auth:
    enablePostgresUser: false
    username: inventree
    database: inventree

redis:
  enabled: true
  auth:
    enabled: false

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 80
        targetPort: http

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: false
    advancedMounts:
      main:
        update:
          - path: /home/inventree/data
        main:
          - path: /var/www
        server:
          - path: /home/inventree/data
        worker:
          - path: /home/inventree/data
