#
# IMPORTANT NOTE
#
# This chart inherits from a common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

controllers:
  main:
    statefulset:
      podManagementPolicy: Parallel
    containers:
      main:
        image:
          # -- image repository
          repository: ghcr.io/reitermarkus/strongswan
          # -- image tag
          tag: v1.5.0
          # -- image pull policy
          pullPolicy: IfNotPresent
        # -- environment variables. See more environment variables in the [strongswan documentation](https://github.com/reitermarkus/strongswan).
        # @default -- See below
        env:
          # -- Set the container timezone
          TZ: UTC
          # VPN_NAME: Example VPN # VPN display name.
          # WIFI_SSID: Example WiFi # Disable VPN when connected to this WiFi network.
          # VPN_DOMAIN: vpn.example.org # FQDN for accessing the VPN.
          # VPN_P12_PASSWORD:
          #   valueFrom:
          #     secretKeyRef:
          #       name: strongswan-credentials
          #       key: p12-password
          # WEBSERVER: 'true'
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              exec:
                command: [ipsec, status]
          readiness:
            enabled: true
            custom: true
            spec:
              exec:
                command: [ipsec, status]
          startup:
            enabled: true
            custom: true
            spec:
              exec:
                command: [ipsec, status]
        # -- Security contexts required for container.
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
    pod:
      hostNetwork: true

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    sessionAffinity: ClientIP
    ports:
      http:
        enabled: false
        primary: false
        port: 8000
      isakmp:
        enabled: true
        port: 500
        targetPort: 500
        protocol: UDP
      ike:
        enabled: true
        port: 4500
        targetPort: 4500
        protocol: UDP

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  # -- Single configuration directory.
  config:
    enabled: false
    mountPath: /etc/ipsec.d
  # -- Individual certificate directories.
  cacerts:
    enabled: false
    mountPath: /etc/ipsec.d/cacerts
  certs:
    enabled: false
    mountPath: /etc/ipsec.d/certs
  private:
    enabled: false
    mountPath: /etc/ipsec.d/private
