---
{{- include "bjw-s.common.loader.init" . }}

{{- define "openhab.hardcodedValues" -}}
# Set the nameOverride based on the release name if no override has been set
{{ if not .Values.global.nameOverride }}
global:
  nameOverride: "{{ .Release.Name }}"
{{ end }}

persistence:
  init:
    type: configMap
    name: {{ printf "%v-init" (include "bjw-s.common.lib.chart.names.fullname" .) }}
    globalMounts:
      - path: /etc/cont-init.d/enable-console-logging.sh
        subPath: enable-console-logging.sh
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "openhab.hardcodedValues" . | fromYaml) -}}

{{ include "bjw-s.common.loader.generate" . }}
