---
{{- include "bjw-s.common.loader.init" . }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-init
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
data:
  enable-console-logging.sh: |
    echo 'Enabling console logging.'
    sed -i -E 's|(<AppenderRef ref="OSGI"/>).*|\1<AppenderRef ref="STDOUT"/>|' /openhab/userdata/etc/log4j2.xml
