---
{{- include "bjw-s.common.loader.init" . }}

{{- define "lancache.harcodedValues" -}}
# Set the nameOverride based on the release name if no override has been set
{{ if not .Values.global.nameOverride }}
global:
  nameOverride: "{{ .Release.Name }}"
{{ end }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "lancache.harcodedValues" . | fromYaml) -}}

{{- define "lancache.harcodedValues2" -}}
{{- $dnsController := (index .Values.controllers "lancache-dns") -}}
{{- $monolithicEnv := .Values.controllers.lancache.containers.monolithic.env -}}
{{- $dnsEnv := $dnsController.containers.dns.env -}}
{{ if ne $dnsController.enabled false }}
controllers:
  lancache-dns:
    containers:
      dns:
        env:
          {{- if $monolithicEnv.TZ }}
          TZ: {{ $monolithicEnv.TZ | quote }}
          {{- end }}
          {{- if or (not $monolithicEnv.CACHE_MODE) (eq $monolithicEnv.CACHE_MODE "generic") }}
          USE_GENERIC_CACHE: 'true'
          {{- end }}
          {{- if not $dnsEnv.LANCACHE_IP -}}
          {{- if .Values.service.web.loadBalancerIP -}}
          LANCACHE_IP: {{ .Values.service.web.loadBalancerIP | quote }}
          {{- else }}
          LANCACHE_IP: {{ printf "$(%v_SERVICE_HOST)" (include "bjw-s.common.lib.chart.names.fullname" . | upper | replace "-" "_" ) | quote }}
          {{- end }}
          {{- end }}
          {{- if $monolithicEnv.UPSTREAM_DNS }}
          UPSTREAM_DNS: {{ $monolithicEnv.UPSTREAM_DNS | quote }}
          {{- end }}
          {{- if $monolithicEnv.CACHE_DOMAINS_REPO }}
          CACHE_DOMAINS_REPO: {{ $monolithicEnv.CACHE_DOMAINS_REPO | quote }}
          {{- end }}
          {{- if $monolithicEnv.CACHE_DOMAINS_BRANCH }}
          CACHE_DOMAINS_BRANCH: {{ $monolithicEnv.CACHE_DOMAINS_BRANCH | quote }}
          {{- end }}
    pod:
      {{- if and (not $dnsEnv.LANCACHE_IP) (not .Values.service.web.loadBalancerIP) }}
      enableServiceLinks: true
      {{- end }}
{{ else }}
controllers:
  lancache-dns:
    enabled: false
{{ end }}

service:
  dns:
    enabled: {{ and (ne $dnsController.enabled false) (ne .Values.service.dns.enabled false) }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "lancache.harcodedValues2" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}
