---
{{- include "bjw-s.common.loader.init" . }}

{{- define "lancache.harcodedValues" -}}
{{ if .Values.controllers.dns.enabled }}
controllers:
  lancache-dns:
    containers:
      dns:
        env:
          {{- $mainEnv := .Values.controllers.main.containers.main.env -}}
          {{- $dnsEnv := .Values.controllers.dns.containers.dns.env -}}
          {{- if $mainEnv.TZ }}
          TZ: {{ $mainEnv.TZ | quote }}
          {{- end }}
          {{- if or (not $mainEnv.CACHE_MODE) (eq $mainEnv.CACHE_MODE "generic") }}
          USE_GENERIC_CACHE: 'true'
          {{- end }}
          {{- if not $dnsEnv.LANCACHE_IP -}}
          {{- if .Values.service.main.loadBalancerIP -}}
          LANCACHE_IP: {{ .Values.service.main.loadBalancerIP | quote }}
          {{- else }}
          LANCACHE_IP: {{ printf "$(%v_SERVICE_HOST)" (include "bjw-s.common.lib.chart.names.fullname" . | upper | replace "-" "_" ) | quote }}
          {{- end }}
          {{- end }}
          {{- if $mainEnv.UPSTREAM_DNS }}
          UPSTREAM_DNS: {{ $mainEnv.UPSTREAM_DNS | quote }}
          {{- end }}
          {{- if $mainEnv.CACHE_DOMAINS_REPO }}
          CACHE_DOMAINS_REPO: {{ $mainEnv.CACHE_DOMAINS_REPO | quote }}
          {{- end }}
          {{- if $mainEnv.CACHE_DOMAINS_BRANCH }}
          CACHE_DOMAINS_BRANCH: {{ $mainEnv.CACHE_DOMAINS_BRANCH | quote }}
          {{- end }}

service:
  dns:
    enabled: true
{{ end }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "lancache.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}
