---
{{- include "bjw-s.common.loader.init" . }}

{{- define "lancache.harcodedValues" -}}
{{ if .Values.controllers.dns.enabled }}
controllers:
  lancache-dns:
    containers:
      dns:
        env:
          {{- $monolithicEnv := .Values.controllers.lancache.containers.monolithic.env -}}
          {{- $dnsEnv := .Values.controllers.lancache-dns.containers.dns.env -}}
          {{- if $monolithicEnv.TZ }}
          TZ: {{ $monolithicEnv.TZ | quote }}
          {{- end }}
          {{- if or (not $monolithicEnv.CACHE_MODE) (eq $monolithicEnv.CACHE_MODE "generic") }}
          USE_GENERIC_CACHE: 'true'
          {{- end }}
          {{- if not $dnsEnv.LANCACHE_IP -}}
          {{- if .Values.service.web.loadBalancerIP -}}
          LANCACHE_IP: {{ .Values.service.web.loadBalancerIP | quote }}
          {{- else }}
          LANCACHE_IP: {{ printf "$(%v_SERVICE_HOST)" (include "bjw-s.common.lib.chart.names.fullname" . | upper | replace "-" "_" ) | quote }}
          {{- end }}
          {{- end }}
          {{- if $monolithicEnv.UPSTREAM_DNS }}
          UPSTREAM_DNS: {{ $monolithicEnv.UPSTREAM_DNS | quote }}
          {{- end }}
          {{- if $monolithicEnv.CACHE_DOMAINS_REPO }}
          CACHE_DOMAINS_REPO: {{ $monolithicEnv.CACHE_DOMAINS_REPO | quote }}
          {{- end }}
          {{- if $monolithicEnv.CACHE_DOMAINS_BRANCH }}
          CACHE_DOMAINS_BRANCH: {{ $monolithicEnv.CACHE_DOMAINS_BRANCH | quote }}
          {{- end }}

service:
  dns:
    enabled: true
{{ end }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "lancache.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}
