---
apiVersion: v2
appVersion: 1.0.0-beta.16-ba60e37
description: TeamSpeak & Discord Bot
name: sinusbot
version: 1.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - sinusbot
home: https://github.com/reitermarkus/helm-charts/tree/main/charts/stable/sinusbot
icon: https://pbs.twimg.com/profile_images/613423613711122432/fFJZiB_t_400x400.png
sources:
  - https://github.com/sinusbot/sinusbot-docker
maintainers:
  - name: reitermarkus
    email: me@reitermark.us
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 1.1.3
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Updated library chart.
