#
# IMPORTANT NOTE
#
# This chart inherits from a common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

controllers:
  main:
    containers:
      main:
        image:
          # -- image repository
          repository: sinusbot/docker
          # -- image tag
          # @default -- chart.appVersion
          tag:
          # -- image pull policy
          pullPolicy: IfNotPresent
        # -- environment variables. See more environment variables in the [${CHARTNAME} documentation](https://${CHARTNAME}.org/docs).
        # @default -- See below
        env:
          # -- Specify the user ID the application will run as
          UID: "1001"
          # -- Specify the group ID the application will run as
          GID: "1001"
          # OVERRIDE_PASSWORD:
    pod:
      # -- The official SinusBot image is only available for x86_64.
      nodeSelector:
        kubernetes.io/arch: amd64

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8087

# -- Configure persistence settings for the chart under this key. Choose either
# -- a single volume for all data or separate volumes for each sub-directory.
# @default -- See values.yaml
persistence:
  # -- single volume
  sinusbot:
    enabled: false
    subPath:
      - mountPath: /opt/sinusbot/data
        path: data
      - mountPath: /opt/sinusbot/scripts
        path: scripts

  # -- separate volumes
  data:
    enabled: false
    mountPath: /opt/sinusbot/data
  scripts:
    enabled: false
    mountPath: /opt/sinusbot/scripts
