---
{{- include "bjw-s.common.loader.init" . }}

# If there's an existing secret, reuse it, otherwise generate a new one.
{{- define "mumble.superuser-password" -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "bjw-s.common.lib.chart.names.fullname" .) ) -}}
  {{- if $secret -}}
    {{-  index $secret "data" "superuser_password" -}}
  {{- else -}}
    {{- randAlphaNum 32 | b64enc | quote -}}
  {{- end -}}
{{- end -}}

{{- define "mumble.harcodedValues" -}}
# Set the nameOverride based on the release name if no override has been set
{{ if not .Values.global.nameOverride }}
global:
  nameOverride: "{{ .Release.Name }}"
{{ end }}

{{- if not .Values.controllers.main.containers.main.env.MUMBLE_SUPERUSER_PASSWORD }}
controllers:
  main:
    containers:
      main:
        env:
          MUMBLE_SUPERUSER_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
                key: superuser_password
{{- end }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "mumble.harcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}
