{{- $mainEnv := .Values.controllers.mumble.containers.server.env -}}
{{- if (and (not $mainEnv.MUMBLE_CONFIG_SERVER_PASSWORD) (not $mainEnv.MUMBLE_SUPERUSER_PASSWORD)) }}
{{- include "bjw-s.common.loader.init" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
type: Opaque
data:
  superuser_password: {{ template "mumble.superuser-password" . }}
{{- end }}
