---
{{- include "bjw-s.common.loader.init" . }}

{{- define "prometheus-nut-exporter.harcodedValues" -}}
# Set the nameOverride based on the release name if no override has been set
{{- if not .Values.global.nameOverride }}
global:
  nameOverride: "{{ .Release.Name }}"
{{- end }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "prometheus-nut-exporter.harcodedValues" . | fromYaml) -}}

{{- define "prometheus-nut-exporter.harcodedValues2" -}}
service:
  metrics:
    enabled: {{ ne .Values.metrics.enabled false }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "prometheus-nut-exporter.harcodedValues2" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}
