{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
{{- include "bjw-s.common.loader.init" . }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "bjw-s.common.lib.metadata.selectorLabels" . | nindent 6 }}
  endpoints:
    {{- range .Values.metrics.serviceMonitor.targets }}
    - port: http
      {{- with .Values.metrics.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      path: /metrics
      params:
        target:
          - "{{ .hostname }}:{{ .port }}"
      relabelings:
        - sourceLabels: [__param_target]
          targetLabel: target
      {{- end }}
{{- end }}
