---
apiVersion: v2
appVersion: main
description: Dedicated server for 7 Days to Die
name: sdtd
version: 3.6.1
kubeVersion: ">=1.16.0-0"
keywords:
  - sdtd
  - 7d2d
home: https://github.com/reitermarkus/helm-charts/tree/main/charts/sdtd
icon: https://7daystodie.com/wp-content/uploads/2016/04/7dtd_site_icon.png
sources:
  - https://github.com/reitermarkus/7d2d
  - https://ghcr.io/reitermarkus/7d2d
maintainers:
  - name: reitermarkus
    email: me@reitermark.us
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 3.6.1
