#
# IMPORTANT NOTE
#
# This chart inherits from a common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

controllers:
  main:
    containers:
      main:
        image:
          # -- image repository
          repository: openhab/openhab
          # -- image tag
          # @default -- chart.appVersion
          tag:
          # -- image pull policy
          pullPolicy: IfNotPresent
        # -- environment variables. See more environment variables in the [openhab image documentation](https://hub.docker.com/r/openhab/openhab).
        # @default -- See below
        env: {}
          # -- Set the container timezone
          # TZ: UTC
          # EXTRA_JAVA_OPTS: -Duser.timezone=UTC
          # USER_ID: 1000
          # GROUP_ID: 1000
          # CRYPTO_POLICY: unlimited

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        enabled: true
        port: 8080
      https:
        enabled: true
        port: 8443

# -- Configure persistence settings for the chart under this key. Choose either
# -- a single volume for all data or separate volumes for each sub-directory.
# @default -- See values.yaml
persistence:
  # -- single volume
  data:
    enabled: false
    subPath:
      - mountPath: /openhab/addons
        path: addons
      - mountPath: /openhab/conf
        path: conf
      - mountPath: /openhab/userdata
        path: userdata

  # -- separate volumes
  addons:
    enabled: false
    mountPath: /openhab/addons
  conf:
    enabled: false
    mountPath: /openhab/conf
  userdata:
    enabled: false
    mountPath: /openhab/userdata
