---
{{- include "bjw-s.common.loader.init" . }}

{{- define "inventree.sharedEnv" -}}
INVENTREE_DEBUG: 'false'
INVENTREE_TRUSTED_ORIGINS: http://localhost,http://localhost:8000
INVENTREE_DB_NAME: inventree
{{- if .Values.postgresql.enabled }}
INVENTREE_DB_ENGINE: postgresql
INVENTREE_DB_USER: inventree
INVENTREE_DB_PASSWORD:
  valueFrom:
    secretKeyRef:
      name: {{ .Release.Name }}-postgresql
      key: password
INVENTREE_DB_HOST: "{{ .Release.Name }}-postgresql"
INVENTREE_DB_PORT: 5432
{{- else}}
INVENTREE_DB_ENGINE: sqlite
{{- end }}
{{- if .Values.redis.enabled }}
INVENTREE_CACHE_HOST: "{{ .Release.Name }}-redis"
INVENTREE_CACHE_PORT: 6379
{{- end }}
{{ end }}

{{- define "inventree.hardcodedValues" -}}
# Set the nameOverride based on the release name if no override has been set
{{ if not .Values.global.nameOverride }}
global:
  nameOverride: "{{ .Release.Name }}"
{{ end }}

controllers:
  inventree:
    initContainers:
      migrate:
        env:
          {{ include "inventree.sharedEnv" . | nindent 10 }}
    containers:
      server:
        env:
          {{ include "inventree.sharedEnv" . | nindent 10 }}
      worker:
        env:
          {{ include "inventree.sharedEnv" . | nindent 10 }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "inventree.hardcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}
