---
{{- include "bjw-s.common.loader.init" . }}

# If there's an existing secret, reuse it, otherwise generate a new one.
{{- define "inventree.postgres-password" -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%v-postgres" (include "bjw-s.common.lib.chart.names.fullname" .)) ) -}}
  {{- if $secret -}}
    {{-  index $secret "data" "password" -}}
  {{- else -}}
    {{- randAlphaNum 32 | b64enc | quote -}}
  {{- end -}}
{{- end -}}

{{- define "inventree.sharedEnv" -}}
INVENTREE_AUTO_UPDATE: 'True'
INVENTREE_TRUSTED_ORIGINS: http://localhost:8000
INVENTREE_DB_NAME: inventree
{{- if .Values.cnpg.enabled }}
INVENTREE_DB_ENGINE: postgresql
INVENTREE_DB_USER: inventree
INVENTREE_DB_PASSWORD:
  valueFrom:
    secretKeyRef:
      name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-postgres
      key: password
INVENTREE_DB_HOST: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-postgres
INVENTREE_DB_PORT: 5432
{{- else}}
INVENTREE_DB_ENGINE: sqlite
{{- end }}
{{- if (index .Values "redis-ha" "enabled") }}
INVENTREE_CACHE_HOST: "{{ .Release.Name }}-redis-ha"
INVENTREE_CACHE_PORT: 6379
{{- end }}
{{ end }}

{{- define "inventree.hardcodedValues" -}}
# Set the nameOverride based on the release name if no override has been set
{{ if not .Values.global.nameOverride }}
global:
  nameOverride: "{{ .Release.Name }}"
{{ end }}

controllers:
  inventree:
    initContainers:
      migrate:
        env:
          {{ include "inventree.sharedEnv" . | nindent 10 }}
    containers:
      server:
        env:
          {{ include "inventree.sharedEnv" . | nindent 10 }}
      worker:
        env:
          {{ include "inventree.sharedEnv" . | nindent 10 }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "inventree.hardcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}
