{{- include "bjw-s.common.loader.init" . }}
{{- if .Values.cnpg.enabled }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-postgres
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
spec:
  imageName: {{ .Values.cnpg.image.repository }}:{{ .Values.cnpg.image.tag }}

  instances: {{ .Values.cnpg.instances }}

  storage:
    size: {{ .Values.cnpg.storage.size }}

  managed:
    roles:
      - name: inventree
        login: true
        superuser: false
        passwordSecret:
          name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-postgres
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
spec:
  cluster:
    name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-postgres
  name: inventree
  owner: inventree
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-postgres
  labels:
    cnpg.io/reload: 'true'
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  username: {{ printf "inventree" | b64enc | quote }}
  password: {{ template "inventree.postgres-password" . }}
{{- end }}
