#
# IMPORTANT NOTE
#
# This chart inherits from a common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

controllers:
  mumble:
    containers:
      server:
        image:
          # -- image repository
          repository: mumblevoip/mumble-server
          # -- image tag
          tag: "v{{ .Chart.AppVersion }}"
          # -- image pull policy
          pullPolicy: IfNotPresent
        # -- environment variables. See more environment variables in the [mumble-server image documentation](https://github.com/mumble-voip/mumble-docker#configuration).
        # @default -- See below
        env:
          TZ: UTC
          MUMBLE_CONFIG_WELCOMETEXT: <br/>Welcome to this server, running the official Mumble Docker image on Kubernetes.<br/>Enjoy your stay!<br/>
          # MUMBLE_CONFIG_SERVER_PASSWORD:
          #   valueFrom:
          #     secretKeyRef:
          #       name: mumble
          #       key: server_password
          # MUMBLE_SUPERUSER_PASSWORD:
          #   valueFrom:
          #     secretKeyRef:
          #       name: mumble
          #       key: superuser_password
        ports:
          - name: control
            containerPort: 64738
          - name: voice
            containerPort: 64738
            protocol: UDP
        probes:
          liveness:
            enabled: true
            port: control
          readiness:
            enabled: true
            port: control
          startup:
            enabled: true
            port: control
            spec:
              # Database migrations can take a while.
              failureThreshold: 30

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  mumble:
    primary: true
    controller: mumble
    ports:
      control:
        primary: true
        port: 64738
        targetPort: control
      voice:
        port: 64738
        targetPort: voice
        protocol: UDP

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    type: emptyDir
