name: pre-commit

on:
  pull_request:

jobs:
  check:
    name: Run pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Collect changed files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: changed-files
        with:
          list-files: json
          filters: |
            added_or_modified:
              - added|modified: '**'

      - name: Run against changes
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        with:
          extra_args: --files ${{ join(fromJson(steps.changed-files.outputs.added_or_modified_files), ' ') }} --config .github/pre-commit/config.yml
