name: "Pre-commit consistency check"

on:
  workflow_call:
    inputs:
      modifiedFiles:
        description: >
          A JSON encoded array of files to check
        required: true
        type: string

jobs:
  pre-commit-check:
    name: Run pre-commit checks
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Run against changes
        uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # v3.0.0
        with:
          extra_args: --files ${{ join(fromJson(inputs.modifiedFiles), ' ') }} --config .github/pre-commit/config.yml
