#
# IMPORTANT NOTE
#
# This chart inherits from a common library chart. You can check the default values/options here:
# https://github.com/bjw-s-labs/helm-charts/blob/main/charts/library/common/values.yaml
#

controllers:
  inventree:
    initContainers:
      migrate:
        image:
          # -- image repository
          repository: inventree/inventree
          # -- image tag
          tag: "{{ .Chart.AppVersion }}"
          # -- image pull policy
          pullPolicy: IfNotPresent
        command:
          - invoke
          - update
          - --skip-backup
    containers:
      proxy:
        image:
          # -- image repository
          repository: caddy
          # -- image tag
          tag: 2.10.0-alpine
          # -- image pull policy
          pullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 80
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
      server:
        image:
          # -- image repository
          repository: inventree/inventree
          # -- image tag
          tag: "{{ .Chart.AppVersion }}"
          # -- image pull policy
          pullPolicy: IfNotPresent
        # -- environment variables. See more environment variables in the [InvenTree documentation](https://docs.inventree.org/en/latest/start/config/).
        # @default -- See below
        env: {}
          # -- Set the container timezone
          # TZ: UTC
          # -- Set the site URL
          # INVENTREE_SITE_URL: 'http://inventree.localhost'
          # -- Enable plugin support
          # INVENTREE_PLUGINS_ENABLED: 'true'
          # -- Set the admin user name
          # INVENTREE_ADMIN_USER:
          #   valueFrom:
          #     secretKeyRef:
          #       name: inventree
          #       key: admin_user
          # -- Set the admin password
          # INVENTREE_ADMIN_PASSWORD:
          #   valueFrom:
          #     secretKeyRef:
          #       name: inventree
          #       key: admin_password
          # -- Set the admin email
          # INVENTREE_ADMIN_EMAIL:
          #   valueFrom:
          #     secretKeyRef:
          #       name: inventree
          #       key: admin_password
        probes:
          liveness:
            enabled: true
            type: TCP
            port: 8000
          readiness:
            enabled: true
            type: TCP
            port: 8000
          startup:
            enabled: true
            type: TCP
            port: 8000
      worker:
        image:
          # -- image repository
          repository: inventree/inventree
          # -- image tag
          tag: "{{ .Chart.AppVersion }}"
          # -- image pull policy
          pullPolicy: IfNotPresent
        command:
          - invoke
          - worker

postgresql:
  enabled: true
  image:
    tag: 15.5.0
  auth:
    enablePostgresUser: false
    username: inventree
    database: inventree

redis-ha:
  enabled: true
  replicas: 1
  redis:
    config:
      # Disable AOF persistence.
      appendonly: "no"
      # Disable RDB persistence.
      save: '""'

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  web:
    controller: inventree
    ports:
      http:
        port: 80
        targetPort: http

configMaps:
  caddy-config:
    suffix: caddy-config
    data:
      Caddyfile: |-
        {
          servers {
            # Allow running behind another proxy.
            trusted_proxies static private_ranges
            trusted_proxies_strict
          }
        }

        # Logging configuration for Caddy.
        (log_common) {
          log {
            output file /var/log/caddy/{args[0]}.access.log
          }
        }

        # CORS headers control (used for static and media files).
        (cors-headers) {
          header Allow GET,HEAD,OPTIONS
          header Access-Control-Allow-Origin *
          header Access-Control-Allow-Methods GET,HEAD,OPTIONS
          header Access-Control-Allow-Headers Authorization,Content-Type,User-Agent

          @cors_preflight{args[0]} method OPTIONS

          handle @cors_preflight{args[0]} {
            respond "" 204
          }
        }

        :80 {
          import log_common inventree
          encode gzip

          request_body {
            max_size 100MB
          }

          # Handle static request files.
          handle_path /static/* {
            import cors-headers static

            root * /var/www/static
            file_server
          }

          # Handle media request files.
          handle_path /media/* {
            import cors-headers media

            root * /var/www/media
            file_server

            # Force download of media files (for security).
            # Comment out this line if you do not want to force download.
            handle {
              header Content-Disposition attachment
            }
            # Don't force download of images.
            @images {
              path_regexp ^.*\.(jpe?g|j2k|png|bmp|tiff?|webp|gif)$
            }
            handle @images {
              header Content-Disposition inline
            }

            # Authentication is handled by the `forward_auth` directive.
            # This is required to ensure that media files are only accessible to authenticated users.
            forward_auth localhost:8000 {
              uri /auth/
            }
          }

          # All other requests are proxied to the InvenTree server.
          reverse_proxy localhost:8000
        }

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  caddy-config:
    type: configMap
    identifier: caddy-config
    advancedMounts:
      inventree:
        proxy:
          - path: /etc/caddy/Caddyfile
            readOnly: true
            subPath: Caddyfile
  data:
    type: emptyDir
    advancedMounts:
      inventree:
        migrate:
          - path: /home/inventree/data
        server:
          - path: /home/inventree/data
        worker:
          - path: /home/inventree/data
        proxy:
          - path: /var/www/static
            subPath: static
          - path: /var/www/media
            subPath: media
          - path: /var/log
          - path: /data
          - path: /config
